<?xml version="1.0"?>
<package format="3">
  <name>lab_robot_control</name>
  <version>0.0.1</version>
  <description>Scaffold package for lab_robot_control.</description>
  <maintainer email="lab@example.com">Lab Scaffold</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ur_simulation_gz</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
