<?xml version="1.0"?>
<package format="3">
  <name>lab_robot_gazebo</name>
  <version>0.0.1</version>
  <description>Scaffold package for lab_robot_gazebo.</description>
  <maintainer email="lab@example.com">Lab Scaffold</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
