<?xml version="1.0"?>
<package format="3">
  <name>lab_utils</name>
  <version>0.0.1</version>
  <description>Scaffold package for lab_utils.</description>
  <maintainer email="lab@example.com">Lab Scaffold</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
